## <center>Experment 4</center>

### <center>DATA MANIPULATION WITH PANDAS</center>

**Aim:**
   
   To perform data manipulation operations such as selecting, filtering, sorting, updating, and creating new columns using the Pandas
library on students dataset.

**PREREQUISITES & REQUIREMENTS:**
1. Computer with Python Installed
2. Jupytor Notebook
3. Knowledge on Python & Pandas Libraries

**Step 1:** Install and import the Pandas Library using the commands:

pip install pandas

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# importing pandas 
import pandas as pd

**Step 2:** Importing the Dataset

In [3]:
df_sunil = pd.read_csv('ipl2024-Matches-with-runrate.csv')

In [4]:
# Reading the head of the Dataset
df_sunil.head()

,id,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
0,1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman,8.65,8.80,8.725
1,2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav,8.70,8.85,8.775
2,3,"March 23,2024",Kolkata,Hyderabad,Hyderabad,Field,208,7,204,7,Kolkata,Andre Russell,Andre Russell,T Natarajan,10.40,10.20,10.300
3,4,"March 24,2024",Rajasthan,Lucknow,Rajasthan,Bat,193,4,173,6,Rajasthan,Sanju Samson,Sanju Samson,Trent Boult,9.65,8.65,9.150
4,5,"March 24,2024",Gujarat,Mumbai,Mumbai,Field,168,6,162,9,Gujarat,Sai Sudharsan,Dewald Brevis,Jasprit Bumrah,8.40,8.10,8.250

In [6]:
# Set Index for the DataFrame (unique identifier)
df_sunil = df_sunil.set_index('id')

In [7]:
#Info of the DtaFrame
df_sunil.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74 entries, 1 to 74
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     74 non-null     object
 1   team1                    74 non-null     object
 2   team2                    74 non-null     object
 3   toss_winner              74 non-null     object
 4   decision                 71 non-null     object
 5   first_score              74 non-null     int64
 6   first_wkts               74 non-null     int64
 7   second_score             74 non-null     int64
 8   second_wkts              74 non-null     int64
 9   winner                   74 non-null     object
 10  player_of_the_match      71 non-null     object
 11  most_runs                71 non-null     object
 12  most_wkts                71 non-null     object
 13  run_rate_of_match        71 non-null     float64
 14  run_rate_second_innings  71 non-null     float64
 15  avg_run_rate_match       71 non-null     float64
dtypes: float64(3), int64(4), object(9)
memory usage: 9.8+ KB

**Step 3:** Columns & Rows Selection

In [9]:
# Selecting a Single column
df_sunil[['team1']]

        team1
id
1    Banglore
2       Delhi
3     Kolkata
4   Rajasthan
5     Gujarat
..        ...
70  Rajasthan
71  Hyderabad
72   Banglore
73  Hyderabad
74  Hyderabad

[74 rows x 1 columns]

In [10]:
#selecting multiple columns
df_sunil[['date','team1',]].head()

             date      team1
id
1   March 22,2024   Banglore
2   March 23,2024      Delhi
3   March 23,2024    Kolkata
4   March 24,2024  Rajasthan
5   March 24,2024    Gujarat

In [11]:
#Selecting by row indexing iloc (postion-based)
df_sunil.iloc[1:6]

,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
id,,,,,,,,,,,,,,,,
2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav,8.70,8.85,8.775
3,"March 23,2024",Kolkata,Hyderabad,Hyderabad,Field,208,7,204,7,Kolkata,Andre Russell,Andre Russell,T Natarajan,10.40,10.20,10.300
4,"March 24,2024",Rajasthan,Lucknow,Rajasthan,Bat,193,4,173,6,Rajasthan,Sanju Samson,Sanju Samson,Trent Boult,9.65,8.65,9.150
5,"March 24,2024",Gujarat,Mumbai,Mumbai,Field,168,6,162,9,Gujarat,Sai Sudharsan,Dewald Brevis,Jasprit Bumrah,8.40,8.10,8.250
6,"March 25,2024",Punjab,Banglore,Banglore,Field,176,6,178,6,Banglore,Virat Kohli,Virat Kohli,Harpreet Brar,8.80,8.90,8.850

In [12]:
df_sunil.loc[2]

date                       March 23,2024
team1                              Delhi
team2                             Punjab
toss_winner                       Punjab
decision                           Field
first_score                          174
first_wkts                             9
second_score                         177
second_wkts                            6
winner                            Punjab
player_of_the_match           Sam Curran
most_runs                     Sam Curran
most_wkts                  Kuldeep Yadav
run_rate_of_match                    8.7
run_rate_second_innings             8.85
avg_run_rate_match                 8.775
Name: 2, dtype: object

**Step 4:** Manipulating Data based on Columns

In [13]:
df_sunil.head(6)

,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
id,,,,,,,,,,,,,,,,
1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman,8.65,8.80,8.725
2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav,8.70,8.85,8.775
3,"March 23,2024",Kolkata,Hyderabad,Hyderabad,Field,208,7,204,7,Kolkata,Andre Russell,Andre Russell,T Natarajan,10.40,10.20,10.300
4,"March 24,2024",Rajasthan,Lucknow,Rajasthan,Bat,193,4,173,6,Rajasthan,Sanju Samson,Sanju Samson,Trent Boult,9.65,8.65,9.150
5,"March 24,2024",Gujarat,Mumbai,Mumbai,Field,168,6,162,9,Gujarat,Sai Sudharsan,Dewald Brevis,Jasprit Bumrah,8.40,8.10,8.250
6,"March 25,2024",Punjab,Banglore,Banglore,Field,176,6,178,6,Banglore,Virat Kohli,Virat Kohli,Harpreet Brar,8.80,8.90,8.850

In [112]:
# List of columns with score
Total_score = ['first_score','second_score']

In [18]:
#Rounding Attendance to 2 Decimal Points
df_sunil['avg_run_rate_match'] = df_sunil['avg_run_rate_match'].round(2)
df_sunil.head(2)

,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
id,,,,,,,,,,,,,,,,
1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman,8.65,8.80,8.73
2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav,8.70,8.85,8.77

**Step 5:** Conditional Filtering

In [19]:
# Top 2 Teams with avg_run_rate_match >8
df_sunil[df_sunil['avg_run_rate_match'] > 8].head(2)

,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
id,,,,,,,,,,,,,,,,
1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman,8.65,8.80,8.73
2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav,8.70,8.85,8.77

In [20]:
# Teams  from 'Delhi' OR from 'chennai'
df_sunil[(df_sunil['team1'] == 'Delhi') | (df_sunil['team2'] == 'Chennai')].head()

,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
id,,,,,,,,,,,,,,,,
1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman,8.65,8.80,8.73
2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav,8.70,8.85,8.77
13,"March 31,2024",Delhi,Chennai,Delhi,Bat,191,5,171,6,Delhi,Khaleel Ahmed,Jos Buttler,Mukesh Kumar,9.55,8.55,9.05
22,"April 8,2024",Kolkata,Chennai,Chennai,Field,137,9,141,3,Chennai,Ravindra Jadeja,Ruturaj Gaikwad,Ravindra Jadeja,6.85,7.05,6.95
40,"April 24,2024",Delhi,Gujarat,Gujarat,Field,224,4,220,8,Delhi,Rishabh Pant,Rishabh Pant,Sandeep Warrier,11.20,11.00,11.10

In [21]:
#Teams who winners and they must be from runrate >8
df_sunil[(df_sunil['avg_run_rate_match'] >=8 ) & (df_sunil['winner'] == 'Chennai' )]

,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
id,,,,,,,,,,,,,,,,
1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman,8.65,8.80,8.73
7,"March 26,2024",Chennai,Gujarat,Gujarat,Field,206,6,143,8,Chennai,Shivam Dube,Shivam Dube,Tushar Deshpande,10.30,7.15,8.73
29,"April 14,2024",Chennai,Mumbai,Mumbai,Field,206,4,186,6,Chennai,Matheesha Pathirana,Rohit Sharma,Matheesha Pathirana,10.30,9.30,9.80
46,"April 28,2024",Chennai,Hyderabad,Hyderabad,Field,212,3,134,10,Chennai,Ruturaj Gaikwad,Ruturaj Gaikwad,Tushar Deshpande,10.60,6.70,8.65

In [22]:
# Filtering with Multiple Cities using .isin()
df_sunil[df_sunil['winner'].isin(['Delhi', 'Hyderabad', 'Bangalore'])].head()

,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
id,,,,,,,,,,,,,,,,
8,"March 27,2024",Hyderabad,Mumbai,Mumbai,Field,277,3,246,5,Hyderabad,Abhishek Sharma,Heinrich Klaasen,Pat Cummins,13.85,12.30,13.08
13,"March 31,2024",Delhi,Chennai,Delhi,Bat,191,5,171,6,Delhi,Khaleel Ahmed,Jos Buttler,Mukesh Kumar,9.55,8.55,9.05
18,"April 5,2024",Chennai,Hyderabad,Hyderabad,Field,165,5,166,4,Hyderabad,Abhishek Sharma,Aiden Markram,Moeen Ali,8.25,8.30,8.28
23,"April 9,2024",Hyderabad,Punjab,Punjab,Field,182,9,180,6,Hyderabad,Nitish Kumar Reddy,Nitish Kumar Reddy,Arshdeep Singh,9.10,9.00,9.05
26,"April 12,2024",Lucknow,Delhi,Lucknow,Bat,167,7,170,4,Delhi,Kuldeep Yadav,Ayush Badoni,Kuldeep Yadav,8.35,8.50,8.43

**Step 6:** Sorting Table

In [26]:
#Sorting Table based on a single column - avg_run_rate_match  & Match_Totalscore
df_sunil.sort_values(['avg_run_rate_match', ], ascending=False).head()

,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
id,,,,,,,,,,,,,,,,
8,"March 27,2024",Hyderabad,Mumbai,Mumbai,Field,277,3,246,5,Hyderabad,Abhishek Sharma,Heinrich Klaasen,Pat Cummins,13.85,12.30,13.08
42,"April 26,2024",Kolkata,Punjab,Punjab,Field,261,6,262,2,Punjab,Jonny Bairstow,Jonny Bairstow,Arshdeep Singh,13.05,13.10,13.08
43,"April 27,2024",Delhi,Mumbai,Mumbai,Field,257,4,247,9,Delhi,Jake Fraser-McGurk,Jake Fraser-McGurk,Rasikh Salam,12.85,12.35,12.60
35,"April 20,2024",Hyderabad,Delhi,Delhi,Field,266,7,199,10,Hyderabad,Travis Head,Travis Head,T Natarajan,13.30,9.95,11.62
30,"April 15,2024",Hyderabad,Banglore,Banglore,Field,187,3,262,7,Hyderabad,Travis Head,Travis Head,Pat Cummins,9.35,13.10,11.22

**Step 7:** Updating Data in the Table

In [27]:
#Updating Hyderabad as Hyd in winner Column
df_sunil['winner'] = df_sunil['winner'].replace(['Hyderabad'],['Hyd'])

In [28]:
df_sunil[df_sunil['winner']=='Hyd'].head()

,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match
id,,,,,,,,,,,,,,,,
8,"March 27,2024",Hyderabad,Mumbai,Mumbai,Field,277,3,246,5,Hyd,Abhishek Sharma,Heinrich Klaasen,Pat Cummins,13.85,12.30,13.08
18,"April 5,2024",Chennai,Hyderabad,Hyderabad,Field,165,5,166,4,Hyd,Abhishek Sharma,Aiden Markram,Moeen Ali,8.25,8.30,8.28
23,"April 9,2024",Hyderabad,Punjab,Punjab,Field,182,9,180,6,Hyd,Nitish Kumar Reddy,Nitish Kumar Reddy,Arshdeep Singh,9.10,9.00,9.05
30,"April 15,2024",Hyderabad,Banglore,Banglore,Field,187,3,262,7,Hyd,Travis Head,Travis Head,Pat Cummins,9.35,13.10,11.22
35,"April 20,2024",Hyderabad,Delhi,Delhi,Field,266,7,199,10,Hyd,Travis Head,Travis Head,T Natarajan,13.30,9.95,11.62

In [29]:
# Updating Match total score 23 to 550
df_sunil.loc[23, 'Match_Totalscore'] = 550
print(df_sunil.loc[23]['Match_Totalscore'])

550.0

In [30]:
#Changing the Column Name
df_sunil = df_sunil.rename(columns={'first_score': 'firstinnings_score', 'second_score':'secondinnings_score', })
df_sunil.head(1)

,date,team1,team2,toss_winner,decision,firstinnings_score,first_wkts,secondinnings_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,run_rate_of_match,run_rate_second_innings,avg_run_rate_match,Match_Totalscore
id,,,,,,,,,,,,,,,,,
1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman,8.65,8.8,8.73,NaN

**RESULT:**
By using the Pandas library, various data manipulation techniques such as selecting specific rows and columns, rounding and updating values,
Conditional filtering and renaming columns were successfully implemented on the student dataset.