### <center>CREATING DATAFRAMES & ANALYZING PROPERTIES</center>

<b>AIM:</b>

To create Pandas DataFrames using NumPy arrays, CSV/Excel files and analyze the various properties of the DataFrames for
real world structured data analysis.

<b>PREREQUISITES & REQUIREMENTS:</b>

1. Computer with Python Installed
2. Jupytor Notebook
3. Knowledge of Python, Numpy & Pandas Libraries

**Step 1:** Install and Import the Libraries using commands:

1.pip install numpy

2.pip install pandas

In [15]:
#importing Numpy & pandas
import numpy as np
import pandas as pd

**Step 2:** Create a 2-D array

In [16]:
# Considering a 4-week bike sales data in three different branches
# rows --> branches, columns --> weeks
sales = np.array([[160, 240, 176, 230],
                  [170, 120, 145, 280],
                  [168, 235, 175, 275]])

In [17]:
#sales array properties
sales.shape, sales.ndim

((3, 4), 2)

**Step 3:** Converting the created 2-D array into DataFrame using Pandas

In [18]:
df = pd.DataFrame(sales)
df

     0    1    2    3
0  160  240  176  230
1  170  120  145  280
2  168  235  175  275

In [19]:
#creating the index & columns to the Data Frames
#Indexing--> Branchs, Columns-->weeks
df_index = ['Branch_1', 'Branch_2', 'Branch_3']
df_columns = ['week_1', 'week_2','week_3', 'week_4']

In [20]:
#Assing the index & columns to the dataframe
df = pd.DataFrame(data=sales, index=df_index, columns=df_columns)

In [21]:
#created dataframes
df

          week_1  week_2  week_3  week_4
Branch_1     160     240     176     230
Branch_2     170     120     145     280
Branch_3     168     235     175     275

In [22]:
# Adding Week_5 Data (Column)
# Must match number of rows (3 branches)
df['week_5'] = [210, 220, 230]
df

          week_1  week_2  week_3  week_4  week_5
Branch_1     160     240     176     230     210
Branch_2     170     120     145     280     220
Branch_3     168     235     175     275     230

In [23]:
# Add Branch_4 (Row)

branch_4 = pd.DataFrame({
 'week_1': [155],
 'week_2': [205],
 'week_3': [175],
 'week_4': [210],
 'week_5': [225]
}, index=['Branch_4'])

df = pd.concat([df, branch_4])
df

          week_1  week_2  week_3  week_4  week_5
Branch_1     160     240     176     230     210
Branch_2     170     120     145     280     220
Branch_3     168     235     175     275     230
Branch_4     155     205     175     210     225

**Step 4:** Creating a DataFrame with Existing CSV/EXCEL File

In [24]:
# In case the file is not in the same folder, a full path is necessary
# Use the. read_csv method
sunil_df = pd.read_csv('Indian_Kids_Screen_Time.csv')
                        
sunil_df

,Age,Gender,Avg_Daily_Screen_Time_hr,Primary_Device,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Health_Impacts,Urban_or_Rural
0,14,Male,3.99,Smartphone,True,0.42,"Poor Sleep, Eye Strain",Urban
1,11,Female,4.61,Laptop,True,0.30,Poor Sleep,Urban
2,18,Female,3.73,TV,True,0.32,Poor Sleep,Urban
3,15,Female,1.21,Laptop,False,0.39,NaN,Urban
4,12,Female,5.89,Smartphone,True,0.49,"Poor Sleep, Anxiety",Urban
...,...,...,...,...,...,...,...,...
9707,17,Male,3.26,Smartphone,True,0.44,Poor Sleep,Urban
9708,17,Female,4.43,Smartphone,True,0.40,Poor Sleep,Rural
9709,16,Male,5.62,Smartphone,True,0.39,"Poor Sleep, Eye Strain, Anxiety",Rural
9710,17,Male,5.60,TV,True,0.43,Poor Sleep,Urban
9711,15,Female,6.12,TV,True,0.33,Anxiety,Urban

**Step 5:** Analyze the Important Properties of the DataFrames

In [25]:
# To view the first 5 data points
sunil_df.head()

,Age,Gender,Avg_Daily_Screen_Time_hr,Primary_Device,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Health_Impacts,Urban_or_Rural
0,14,Male,3.99,Smartphone,True,0.42,"Poor Sleep, Eye Strain",Urban
1,11,Female,4.61,Laptop,True,0.30,Poor Sleep,Urban
2,18,Female,3.73,TV,True,0.32,Poor Sleep,Urban
3,15,Female,1.21,Laptop,False,0.39,NaN,Urban
4,12,Female,5.89,Smartphone,True,0.49,"Poor Sleep, Anxiety",Urban

In [26]:
# Shape of the DataFrame
sunil_df.shape

(9712, 8)

In [27]:
# Index Range of the DataFrame
sunil_df.index

RangeIndex(start=0, stop=9712, step=1)

In [28]:
# Data Types in the DataFrame
sunil_df.dtypes

Age                                    int64
Gender                                object
Avg_Daily_Screen_Time_hr             float64
Primary_Device                        object
Exceeded_Recommended_Limit              bool
Educational_to_Recreational_Ratio    float64
Health_Impacts                        object
Urban_or_Rural                        object
dtype: object

In [29]:
# Collecting Descriptive statistics of numerical data in a DataFrame.
# It provides summary statistics such as count, mean, standard deviation, Min etc..
sunil_df.describe()

,Age,Avg_Daily_Screen_Time_hr,Educational_to_Recreational_Ratio
count,9712.000000,9712.000000,9712.000000
mean,12.979201,4.352837,0.427226
std,3.162437,1.718232,0.073221
min,8.000000,0.000000,0.300000
25%,10.000000,3.410000,0.370000
50%,13.000000,4.440000,0.430000
75%,16.000000,5.380000,0.480000
max,18.000000,13.890000,0.600000

In [30]:
# Transposing Rows & Columns
sunil_df.head(10).transpose()

,0,1,2,3,4,5,6,7,8,9
Age,14,11,18,15,12,14,17,10,14,18
Gender,Male,Female,Female,Female,Female,Female,Male,Male,Male,Male
Avg_Daily_Screen_Time_hr,3.99,4.61,3.73,1.21,5.89,4.88,2.97,2.74,4.61,3.24
Primary_Device,Smartphone,Laptop,TV,Laptop,Smartphone,Smartphone,TV,TV,Laptop,Tablet
Exceeded_Recommended_Limit,True,True,True,False,True,True,False,True,True,True
Educational_to_Recreational_Ratio,0.42,0.3,0.32,0.39,0.49,0.44,0.48,0.54,0.36,0.48
Health_Impacts,"Poor Sleep, Eye Strain",Poor Sleep,Poor Sleep,NaN,"Poor Sleep, Anxiety",Poor Sleep,NaN,NaN,"Poor Sleep, Anxiety","Poor Sleep, Obesity Risk"
Urban_or_Rural,Urban,Urban,Urban,Urban,Urban,Urban,Rural,Urban,Rural,Urban

***RESULT:***
 
 By using Pandas, DataFrames were successfully created from NumPy arrays and CSV files. Various DataFrame properties such
as shape, column names, index, data types, and statistical summaries were analyzed.